#ifndef BUTTON_STYLES_H
#define BUTTON_STYLES_H

#include "Colors.h"
#include "Fonts.h"
#include "Sizes.h"

enum {
	CAT_NONE,
	CAT_TEXT
};

struct ButtonStyle {
	float cornerRadius, outlineWidth; // Proportion of (screen height * 2)
	const col& baseColor;
	const col& hoverColor;
	const col& pressedColor;
	const col& outlineColor;

	const Font& font;
	float fontSize; // Proportion of button height
	const col& fontColor;

	byte category = CAT_NONE;
};

const ButtonStyle BS_BASIC = {
0, 0,
WHITE, WHITE, WHITE,
INVISIBLE,
BAHNSCHRIFT, 0.6f, BLACK};

const ButtonStyle BS_INVISIBLE = {
0, 0,
INVISIBLE, INVISIBLE, INVISIBLE,
INVISIBLE,
NONE, 0, INVISIBLE};

const ButtonStyle BS_PANEL = {
0, 0,
DARK_GREY, DARK_GREY, DARK_GREY,
INVISIBLE,
NONE, 0, INVISIBLE};

const ButtonStyle BS_GREY = {
0.05f, 0.01f,
GREY_T, GREY_T_HOVER, GREY_T_PRESSED,
BLACK,
BAHNSCHRIFT, 0.6f, BLACK};
const ButtonStyle BS_GREY_BACKING = {
0.05f, 0.01f,
GREY_T_PRESSED, GREY_T_PRESSED, GREY_T_PRESSED,
BLACK,
BAHNSCHRIFT, 0.6f, BLACK};
const ButtonStyle BS_RED = {
0.05f, 0.01f,
RED_T, RED_T_HOVER, RED_T_PRESSED,
BLACK,
BAHNSCHRIFT, 0.6f, BLACK};
const ButtonStyle BS_GREEN = {
0.05f, 0.01f,
GREEN_T, GREEN_T_HOVER, GREEN_T_PRESSED,
BLACK,
BAHNSCHRIFT, 0.6f, BLACK};

const ButtonStyle BS_TEXT_BOX = {
0, 0.005f,
TEXT_BOX, TEXT_BOX_HOVER, TEXT_BOX_ACTIVE,
BLACK,
COURIER_NEW, 0.8f, TEXT_INACTIVE,
CAT_TEXT};
const ButtonStyle BS_TEXT_BOX_ACTIVE = {
0, 0.005f,
TEXT_BOX_ACTIVE, TEXT_BOX_ACTIVE, TEXT_BOX_ACTIVE,
WHITE,
COURIER_NEW, 0.8f, TEXT_ACTIVE,
CAT_TEXT};
const ButtonStyle BS_TEXT_BOX_STATEFUL = {
0, 0.005f,
STATE, STATE_HOVER, STATE_ACTIVE,
BLACK,
COURIER_NEW, 0.8f, TEXT_INACTIVE,
CAT_TEXT};
const ButtonStyle BS_TEXT_BOX_STATEFUL_ACTIVE = {
0, 0.005f,
STATE_ACTIVE, STATE_ACTIVE, STATE_ACTIVE,
WHITE,
COURIER_NEW, 0.8f, TEXT_ACTIVE,
CAT_TEXT};
const ButtonStyle BS_SEMI_STATEFUL_BLOB = {
SEMI_STATEFUL_BLOB_RADIUS, 0,
STATE_INSTANT, STATE_INSTANT, STATE_INSTANT,
INVISIBLE,
NONE, 0, INVISIBLE};
const ButtonStyle BS_TEXT_HIGHLIGHT = {
0, 0,
TEXT_HIGHLIGHT, TEXT_HIGHLIGHT, TEXT_HIGHLIGHT,
INVISIBLE,
NONE, 0, INVISIBLE,
CAT_TEXT};

const ButtonStyle BS_SELECT = {
0, OUTLINE_WIDTH,
SELECT_BOX, SELECT_BOX, SELECT_BOX,
SELECTED,
NONE, 0, SELECTED};

const ButtonStyle BS_PIVOT = {
PIVOT_RADIUS, 0,
SELECTED, SELECTED, SELECTED,
INVISIBLE,
NONE, 0, INVISIBLE};
const ButtonStyle BS_PIVOT_FOCUSED = {
PIVOT_RADIUS, 0,
FOCUSED, FOCUSED, FOCUSED,
INVISIBLE,
NONE, 0, INVISIBLE};

const ButtonStyle BS_OB_BLOB_TERMINAL = {
0.005f, 0.003f,
OB_BLOB_TERMINAL, OB_BLOB_TERMINAL_HOVER, OB_BLOB_TERMINAL_PRESSED,
BLACK,
NONE, 0, INVISIBLE};
const ButtonStyle BS_OB_BLOB_TERMINAL_ACTIVE = {
0.005f, 0.003f,
OB_BLOB_TERMINAL_PRESSED, OB_BLOB_TERMINAL_PRESSED, OB_BLOB_TERMINAL_PRESSED,
BLACK,
NONE, 0, INVISIBLE};
const ButtonStyle BS_OB_BLOB_CENTRAL = {
0.005f, 0.003f,
OB_BLOB_CENTRAL, OB_BLOB_CENTRAL_HOVER, OB_BLOB_CENTRAL_PRESSED,
BLACK,
NONE, 0, INVISIBLE};
const ButtonStyle BS_OB_BLOB_CENTRAL_ACTIVE = {
0.005f, 0.003f,
OB_BLOB_CENTRAL_PRESSED, OB_BLOB_CENTRAL_PRESSED, OB_BLOB_CENTRAL_PRESSED,
BLACK,
NONE, 0, INVISIBLE};

const ButtonStyle BS_TOGGLE = {
TOGGLE_RADIUS, 0,
STATE, STATE, STATE, // Set every frame
INVISIBLE,
NONE, 0, INVISIBLE};

const ButtonStyle BS_TOGGLE_BLOB = {
TOGGLE_BLOB_RADIUS, 0,
TOGGLE_BLOB, TOGGLE_BLOB, TOGGLE_BLOB,
INVISIBLE,
NONE, 0, INVISIBLE};

#endif // BUTTON_STYLES_H